apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  # need update
  fileSystemId: fs-0cd9acf12c48d49bf
  directoryPerms: "700"
  # Access points are created under this path, one per PVC.
  basePath: "/dynamic"
  subPathPattern: "${.PVC.namespace}/${.PVC.name}"
  ensureUniqueDirectory: "false"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
