kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: desktop

nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /run/desktop/mnt/host/c/Users/simon/OneDrive/Tech/Github/kubeflow-yolo/data
        containerPath: /data
        readOnly: true
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
