---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-cpu-pvc
  namespace: kubeflow-yolo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: notebook-cpu
  namespace: kubeflow-yolo
  labels:
    app: notebook-cpu
    kfp-api-token: "true"
spec:
  template:
    spec:
      nodeSelector:
        workload-class: general
      serviceAccountName: default-editor

      containers:
        - name: notebook
          image: ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-scipy:v1.11.0
          imagePullPolicy: IfNotPresent

          env:
            - name: YOLO_CONFIG_DIR
              value: /home/jovyan/.ultralytics
            - name: AWS_REGION
              value: ca-central-1

          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "2"
              memory: 8Gi

          volumeMounts:
            - name: workspace
              mountPath: /home/jovyan

      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: notebook-cpu-pvc
