# eso resources - ClusterSecretStore + ExternalSecrets, after ESO CRDs exist
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-eso-resources
  namespace: argocd
  labels:
    scope: platform
    capability: security
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/kubeflow-yolo
    targetRevision: master
    path: argocd/eso-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        maxDuration: 3m
        factor: 2
