# istio installation - parent app, syncs the child Applications in argocd/istio
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istio
  namespace: argocd
  labels:
    scope: platform
    capability: network
  annotations:
    argocd.argoproj.io/sync-wave: "16"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/kubeflow-yolo
    targetRevision: master
    path: argocd/istio
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        maxDuration: 3m
        factor: 2
