# Project tenant: Profile + LimitRange.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-tenant
  namespace: argocd
  labels:
    scope: kubeflow
    capability: ml-platform
  annotations:
    argocd.argoproj.io/sync-wave: "39"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/kubeflow-yolo
    targetRevision: master
    path: argocd/kubeflow/tenant
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        maxDuration: 3m
        factor: 2
