apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-nvidia-device-plugin
  namespace: argocd
  labels:
    scope: platform
    capability: compute
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.20.0
    helm:
      releaseName: nvidia-device-plugin
      # nvidia plugin installed only in gpu node
      values: |
        nodeSelector:
          workload-class: gpu

        tolerations:
          - key: workload-class
            operator: Equal
            value: gpu
            effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
