apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-storage-classes
  namespace: argocd
  labels:
    scope: platform
    capability: storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/kubeflow-yolo
    targetRevision: master
    path: argocd/storageclass
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - Force=true
