# Kubeflow Notebook controller
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-controller
  namespace: argocd
  annotations:
    # Sync wave 3
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: "26.03.1"
    path: applications/notebooks-v1/upstream/notebook-controller/overlays/standalone

  destination:
    server: https://kubernetes.default.svc
    namespace: notebook-controller-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        maxDuration: 3m
        factor: 2
