# istio ingress gateway
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istio-gateway
  namespace: argocd
  labels:
    scope: platform
    capability: network
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.30.3
    helm:
      releaseName: istio-ingressgateway
      values: |
        nodeSelector:
          workload-class: platform
        tolerations:
          - key: workload-class
            operator: Equal
            value: platform
            effect: NoSchedule
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "2"
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  ignoreDifferences:
    - group: ""
      kind: Service
      name: istio-ingressgateway
      jsonPointers:
        - /spec/loadBalancerSourceRanges
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
